## Module 2 Python Essentials 2 Quiz

1. The part of your code where you think an exception may occur should be placed inside:
> the `try:` branch

2. The part of your code where the handling of an exception takes place should be placed inside:
> the `except:` branch

3. Choose the true statements. (Select two answers)
> - Different `exception:` branches **must** have unique exception names
> - you **can** use multiple `except:` branches to handle multiple exceptions coming from the same `try:` branch

4. When an exception occurs, we say that is has been:
> raised

5. Which of the approachable `except:` branches is taken into consideration when an exception occurs?
> the first matching branch

6. An assertion can be used to:
> stop the program when some data have improper values

7. A code point is:
> a number which makes up a character

8. `isalnum()` checks if a string contains only letters and digits, and this is:
> a method

9. The expression:
```python
'mike' > 'Mike'
```
is
> `True`

10. The `+=` operator, when applied to strings, performs:
> concatenation
